name: Build and deploy .NET application to container app afp-webapp-cms
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: afp-webapp-cms
  CONTAINER_APP_NAME: afp-webapp-cms
  CONTAINER_APP_RESOURCE_GROUP_NAME: afp
  CONTAINER_REGISTRY_LOGIN_SERVER: afpacr.azurecr.io
  DOCKER_FILE_PATH: Dockerfile
  PROJECT_NAME_FOR_DOCKER: umbraco.web.ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.afpacr_USERNAME_FFFF }}
        password: ${{ secrets.afpacr_PASSWORD_FFFF }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
        